### ISSUE TITLE
Unable to install 4.1.0 due to missing `@types/error-stack-parser` package

### ISSUE THREAD

**Issue by EvHaus** [inikulin/callsite-record#10]
Trying to install `callsite-record@4.1.0` gives me the following error:

```
Error: http://sinopia.cumul8.lan:4873/@types%2ferror-stack-parser: no such package available
    at Request.params.callback [as _callback] (/usr/local/Cellar/yarn/1.0.2/libexec/lib/cli.js:60302:18)
    at Request.self.callback (/usr/local/Cellar/yarn/1.0.2/libexec/lib/cli.js:117370:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/usr/local/Cellar/yarn/1.0.2/libexec/lib/cli.js:118353:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/usr/local/Cellar/yarn/1.0.2/libexec/lib/cli.js:118273:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
Error: http://sinopia.cumul8.lan:4873/@types%2flodash: no such package available
    at Request.params.callback [as _callback] (/usr/local/Cellar/yarn/1.0.2/libexec/lib/cli.js:60302:18)
    at Request.self.callback (/usr/local/Cellar/yarn/1.0.2/libexec/lib/cli.js:117370:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/usr/local/Cellar/yarn/1.0.2/libexec/lib/cli.js:118353:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/usr/local/Cellar/yarn/1.0.2/libexec/lib/cli.js:118273:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)

```

**Comment by inikulin** [comment]
Have you tried installing it with npm?

**Comment by EvHaus** [comment]
Yeah, similar issue.

```
$ npm install callsite-record@4.1.0
npm ERR! code E404
npm ERR! 404 Not Found: @types/chalk@^0.4.31

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ev.haus/.npm/_logs/2017-09-22T22_28_26_315Z-debug.log
```

**Comment by inikulin** [comment]
Unfortunately I can't reproduce this on my side. I've noticed that yarn tries to fetch packages from `http://sinopia.cumul8.lan:4873`. Do you have some npm proxy set?

**Comment by EvHaus** [comment]
Ah, yes... We use `sinopia`. Which doesn't support namespaces packages. Sorry to bother.
